export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET"

export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST"
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS"
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL"
export const PAY_ORDER_RESET = "PAY_ORDER_RESET"

export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST"
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS"
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL"

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST"
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS"
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL"