export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const USER_DETAILS_FOR_ADMIN_REQUEST = "USER_DETAILS_FOR_ADMIN_REQUEST"
export const USER_DETAILS_FOR_ADMIN_SUCCESS = "USER_DETAILS_FOR_ADMIN_SUCCESS"
export const USER_DETAILS_FOR_ADMIN_FAIL = "USER_DETAILS_FOR_ADMIN_FAIL"
export const USER_DETAILS_FOR_ADMIN_RESET = "USER_DETAILS_FOR_ADMIN_RESET"

export const USER_EDIT_PROFILE_REQUEST = "USER_EDIT_PROFILE_REQUEST"
export const USER_EDIT_PROFILE_SUCCESS = "USER_EDIT_PROFILE_SUCCESS"
export const USER_EDIT_PROFILE_FAIL = "USER_EDIT_PROFILE_FAIL"
export const USER_EDIT_PROFILE_RESET = "USER_EDIT_PROFILE_RESET"